#!/bin/bash

export CLASSPATH=`$HADOOP_HOME/bin/hadoop classpath --glob`

#export JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
#export PATH=$PATH:$JAVA_HOME/bin
#export HADOOP_HOME=/home/mbalaz/hadoop-3.2.1
#export HADOOP_INSTALL=$HADOOP_HOME
#export HADOOP_MAPRED_HOME=$HADOOP_HOME
#export HADOOP_COMMON_HOME=$HADOOP_HOME
#export HADOOP_HDFS_HOME=$HADOOP_HOME
#export YARN_HOME=$HADOOP_HOME
#export HADOOP_COMMON_LIB_NATIVE_DIR=$HADOOP_HOME/lib/native
#export PATH=$PATH:$HADOOP_HOME/sbin:$HADOOP_HOME/bin
#export HADOOP_OPTS="-Djava.library.path=$HADOOP_HOME/lib/native"
#export CLASSPATH=`$HADOOP_HOME/bin/hadoop classpath --glob`
#export ARROW_LIBHDFS_DIR=$HADOOP_HOME/lib/native
